Pessoa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('candidato/cadastro', views.cadastro, name='cadastro'),
    path('candidato/area_restrita', views.area_restrita, name='area_restrita'),
    
]

Vagas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('vagas/pesquisa_vagas', views.pesquisa_vagas, name='pesquisa_vagas'),
]

rh_vagas/urls.py
from django.contrib import admin
from django.urls import path
from .apis import PessoasView, VagasView, UsuarioView, CustomAuthToken, UploadCurriculum, CurriculumPDFView
from . import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name="login"),
    path('', views.logout, name="logout"),
    path('api/token/', CustomAuthToken.as_view(), name='token'),
    path('api/pessoas/', PessoasView.as_view(), name='pessoas'),
    path('api/usuario/', UsuarioView.as_view(), name='usuarios'),
    path('api/vagas/', VagasView.as_view(), name='vagas'),
    path('api/curriculum/', UploadCurriculum.as_view(), name='curriculums'),
    path('api/open_curriculum/<int:pk>', CurriculumPDFView.as_view(), name='open_curriculum'),
    path('Pessoa', include(('Pessoa.urls', 'Pessoa'), namespace='Pessoa')),
    path('Vagas', include(('Vagas.urls', 'Pessoa'), namespace='Vagas')),
]

Pessoa/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Pessoa(models.Model):
    
    CHOICES_SEXO = (       
        (0, "Não binário"),             
        (1, "Feminino"),
        (2, "Masculino")
    )
    
    usuario = models.ForeignKey(User,on_delete=models.CASCADE, null=True, blank=True, related_name="pessoa")
    nome = models.CharField(max_length=30, null=True, blank=True)
    sobrenome = models.CharField(max_length=30, null=True, blank=True)
    data_nascimento = models.DateField(null=True, blank=True, verbose_name="Data de Nascimento")
    sexo = models.IntegerField(choices=CHOICES_SEXO, default=0)
    telefone = models.CharField(max_length=12, null=True, blank=True)
    email = models.CharField(max_length=30, null=True, blank=True)

Pessoa/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.contrib import messages
from django.shortcuts import render, redirect, reverse
import requests
import string
import random
from django.contrib.auth.decorators import login_required
from django import forms
from django.core.validators import FileExtensionValidator
from Vagas.models import Vagas
from Curriculum.models import Curriculum
from Pessoa.models import Pessoa

class UploadForm(forms.Form):
    arquivo = forms.FileField(required=False,validators=[FileExtensionValidator(allowed_extensions=['pdf'])])

def handle_uploaded_file(f,nome_arquivo):
    with open(nome_arquivo, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)

def geraUsuario():
    qtde = 8
    return ''.join(random.SystemRandom().choice(string.ascii_letters + string.digits) for _ in range(qtde))

def cadastro(request):
    if request.POST:
        nome = request.POST.get("nome")
        sobrenome = request.POST.get("sobrenome")
        nascimento = request.POST.get("nascimento")
        telefone = request.POST.get("telefone")
        sexo = request.POST.get("sexo")
        email = request.POST.get("email")

        codigo = geraUsuario()
        payload_user = {'username': codigo, 'password': codigo, 'email': email, 'is_active': True}
        cad_user = requests.post('http://127.0.0.1:8000/api/usuario/',data=payload_user)
        if cad_user.status_code in [200, 201]:
            retorno = cad_user.json()
            
            payload = {
                'nome': nome, 
                'sobrenome': sobrenome, 
                'data_nascimento': nascimento, 
                'telefone': telefone, 
                'sexo': sexo, 
                'email': email,
                'usuario': retorno.get("id")}
            
            cad_pessoa = requests.post('http://127.0.0.1:8000/api/pessoas/',data=payload)

            if cad_pessoa.status_code in [200, 201]:
                messages.success(request, 'Cadastro realizado com sucesso. Usuário: {0} e Senha: {0}'.format(codigo))
                return redirect(reverse('Pessoa:cadastro'))
                
            else:
                messages.error(request, 'Ocorreu um erro, verifique se os dados estão corretos e tente novamente!')
        else:
                messages.error(request, 'Ocorreu um erro, verifique se os dados estão corretos e tente novamente!')

    context = {}
    return render(request, 'Pessoa/cadastro.html', context)

@login_required
def area_restrita(request):
    # Recuperando todas as vagas disponíveis
    vagas = {}
    pessoas = {}
    curriculos = {}
    
    todas_vagas = requests.get('http://127.0.0.1:8000/api/vagas/')

    if todas_vagas.status_code in [200, 201]:
        vagas = todas_vagas.json()

    #Recuperando todas as pessoas cadastradas
    
    todas_pessoas = requests.get('http://127.0.0.1:8000/api/pessoas/')

    if todas_pessoas.status_code in [200, 201]:
        pessoas = todas_pessoas.json()

    # Recuperando o arquivo pdf do curriculo
    pessoa = Pessoa.objects.filter(usuario = request.user)
    if len(pessoa) > 0:
        params = {'pessoa': pessoa[0].id}
    
        file_curriculo = requests.get('http://127.0.0.1:8000/api/curriculum/', params=params)
        if file_curriculo.status_code in [200, 201]:
            curriculos = file_curriculo.json()

    form = UploadForm()
    pessoa = request.user.pessoa.first()
    
    if request.POST:
        if request.POST.get("titulo") or request.POST.get("descricao") or request.POST.get("requisitos"): 
            # Cadastro de vagas
            titulo = request.POST.get("titulo")
            descricao = request.POST.get("descricao")
            requisitos = request.POST.get("requisitos")

            payload = {
                    'titulo': titulo, 
                    'descricao': descricao, 
                    'requisitos': requisitos,
                    'disponivel': True
            }

            cad_vagas = requests.post('http://127.0.0.1:8000/api/vagas/',data=payload)

            if cad_vagas.status_code in [200, 201]:
                return redirect(reverse('Pessoa:area_restrita'))
                #messages.success(request, 'Cadastro realizado com sucesso')
            else:
                messages.error(request, 'Ocorreu um erro, verifique se os dados estão corretos e tente novamente!')

        # Cadastro de curriculo
        if request.FILES:
            arquivo = request.FILES.get('arquivo')
            handle_uploaded_file(request.FILES['arquivo'],'media/curriculo-{0}'.format(arquivo.name))
            file = {'file': open('media/curriculo-{0}'.format(arquivo.name), 'rb')}
            payload = {'pessoa': pessoa.id}
            cad_curriculum = requests.post('http://127.0.0.1:8000/api/curriculum/',files=file, data=payload)
            if cad_curriculum.status_code in [200, 201]:
                messages.success(request, 'Cadastro realizado com sucesso')
                return redirect(reverse('Pessoa:area_restrita'))
    
    context = {
        'pessoa': pessoa,
        'form': form,
        'user': request.user,
        'vagas': vagas,
        'pessoas': pessoas,
        'curriculos': curriculos
    }
    return render(request, 'Pessoa/area-restrita.html', context)

templates/Pessoa/area-restrita.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<ul class="nav nav-tabs" id="myTab" role="tablist">
<p>Bem-vindo(a): {%if pessoa.nome%}{{pessoa.nome}}{%else%}{{request.user}}{%endif%}</p>
  {% if user.is_staff == False %}
  <li class="nav-item">
    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#curriculo" role="tab" aria-controls="home" aria-selected="true">Currículo</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#vagas" role="tab" aria-controls="profile" aria-selected="false">Vagas</a>
  </li>
  {% endif %}
  
  {% if user.is_staff == True %}
  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#cadastrarvagas" role="tab" aria-controls="profile" aria-selected="false">Gerenciar Vagas</a>
  </li>

  <li class="nav-item">
    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#pessoascadastradas" role="tab" aria-controls="profile" aria-selected="false">Pessoas Cadastradas</a>
  </li>
  {% endif %}

  <li class="nav-item">
    <a class="nav-link" href="{% url 'logout' %}">Sair</a>
  </li>
  
</ul>
<br />
<div class="tab-content" id="myTabContent">
{% if user.is_staff == False %}
  <div class="tab-pane fade show active" id="curriculo" role="tabpanel" aria-labelledby="home-tab">
   
   <form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Salvar</button>
  </form>
  <ul>
  {% for curriculo in curriculos%}
  <li><a href="http://127.0.0.1:8000/api/open_curriculum/{{curriculo.id}}" target="_blank">{{curriculo.anexo}}</a></li>
  {%endfor%}
  </ul>
  
  
  </div>
  {% endif %}




  <div class="tab-pane fade" id="vagas" role="tabpanel" aria-labelledby="profile-tab">
  <h2>Vagas</h2>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Título</th>
      <th scope="col">Descrição</th>
      <th scope="col">Requisitos</th>
    </tr>
  </thead>
  <tbody>
  {% for vaga in vagas %}
    <tr>
      <td>{{vaga.titulo}}</td>
      <td>{{vaga.descricao}}</td>
      <td>{{vaga.requisitos}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
  </div>





  <div class="tab-pane fade" id="cadastrarvagas" role="tabpanel" aria-labelledby="profile-tab">
<form class="form-cadastro" action="" method="post">
{% csrf_token %}
<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="titulo">Título</label>
            <input type="text" class="form-control" id="titulo" name="titulo">
        </div>
    </div>
</div>
<div class="row"> 

<div class="col-md-12">
        <div class="form-group">
            <label for="descricao">Descrição</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="descricao" id="descricao"></textarea>
        </div>
    </div>

</div>

<div class="row">
    <div class="col-md-12">
        <div class="form-group">
            <label for="requisitos">Requisitos</label>
            <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="requisitos" id="requisitos"></textarea>
        </div>
    </div>
    
</div>

<button type="submit" class="btn btn-primary btn-lg btn-block acessar">Cadastrar</button><br /><br />
<br />
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %} 

<h1>Vagas cadastradas</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Título</th>
      <th scope="col">Descrição</th>
      <th scope="col">Requisitos</th>
    </tr>
  </thead>
  <tbody>
  {% for vaga in vagas %}
    <tr>
      <td>{{vaga.titulo}}</td>
      <td>{{vaga.descricao}}</td>
      <td>{{vaga.requisitos}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

</form>

</div>

  <div class="tab-pane fade" id="pessoascadastradas" role="tabpanel" aria-labelledby="profile-tab">
  <h2>Pessoas cadastradas</h2>
  <table class="table">
  <thead>
    <tr>
      <th scope="col">Nome</th>
      <th scope="col">Sobrenome</th>
      <th scope="col">Data Nascimento</th>
      <th scope="col">Sexo</th>
      <th scope="col">Telefone</th>
      <th scope="col">E-mail</th>
    </tr>
  </thead>
  <tbody>
  {% for pessoa in pessoas %}
    <tr>
      <td>{{pessoa.nome}}</td>
      <td>{{pessoa.sobrenome}}</td>
      <td>{{pessoa.data_nascimento}}</td>
      <td>{{pessoa.get_sexo_display}}</td>
      <td>{{pessoa.telefone}}</td>
      <td>{{pessoa.email}}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>
  
  </div>
</div>
{% endblock %}

templates/Pessoa/cadastro.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

<form class="form-cadastro" action="" method="post">
{% csrf_token %}
<div class="row">
    <div class="col-md-6">
        <div class="form-group">
            <label for="nome">Nome</label>
            <input type="text" class="form-control" id="nome" name="nome">
        </div>
    </div>

    <div class="col-md-6">
        <div class="form-group">
            <label for="sobrenome">Sobrenome</label>
            <input type="text" class="form-control" id="sobrenome" name="sobrenome">
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-4">
        <div class="form-group">
            <label for="nascimento">Data Nascimento</label>
            <input type="date" class="form-control" id="nascimento" name="nascimento">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
                <label for="telefone">Telefone</label>
                <input type="text" class="form-control" id="telefone" name="telefone">
        </div>
    </div>
    <div class="col-md-4">
        <div class="form-group">
            <label for="sexo">Sexo</label>
            <select class="form-control" id="sexo" name="sexo">
            <option selected></option>
            <option value="0">Não Binário</option>
            <option value="1">Feminino</option>
            <option value="2">Masculino</option>
            </select>
        </div>
    </div>
</div>
<br />
<div class="row">
 <div class="col-md-12">
    <div class="form-group">
        <label for="email">Informe o e-mail</label>
        <input type="email" class="form-control" id="email" name="email">
    </div>
</div>
</div>
<br />
<button type="submit" class="btn btn-primary btn-lg btn-block acessar">Cadastrar</button><br /><br />
<a class="btn btn-warning btn-lg btn-block acessar" href="{% url 'login'%}" role="button">Voltar</a>
<br />
{% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %} 
</form>
{% endblock %}