Pessoa/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('candidato/cadastro', views.cadastro, name='cadastro'),
    path('candidato/area_restrita', views.area_restrita, name='area_restrita'),
    
]

Vagas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('vagas/pesquisa_vagas', views.pesquisa_vagas, name='pesquisa_vagas'),
]

rh_vagas/urls.py
from django.contrib import admin
from django.urls import path
from .apis import PessoasView, VagasView, UsuarioView, CustomAuthToken, UploadCurriculum, CurriculumPDFView
from . import views
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.login, name="login"),
    path('', views.logout, name="logout"),
    path('api/token/', CustomAuthToken.as_view(), name='token'),
    path('api/pessoas/', PessoasView.as_view(), name='pessoas'),
    path('api/usuario/', UsuarioView.as_view(), name='usuarios'),
    path('api/vagas/', VagasView.as_view(), name='vagas'),
    path('api/curriculum/', UploadCurriculum.as_view(), name='curriculums'),
    path('api/open_curriculum/<int:pk>', CurriculumPDFView.as_view(), name='open_curriculum'),
    path('Pessoa', include(('Pessoa.urls', 'Pessoa'), namespace='Pessoa')),
    path('Vagas', include(('Vagas.urls', 'Pessoa'), namespace='Vagas')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>|Vagas - RH|</title>
  <meta content="" name="description">
  <meta content="" name="keywords">
  <link href="{% static "style.css" %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/all.min.css' %}">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>

<body>

    <div>
        {% block content %}
        {% endblock %}
    </div>
    
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  
</body>
</html>

templates/login.html
{% extends "base.html" %} 
{% load static %}
{% block content %}

<form class="formulario" action="" method="post">
{% csrf_token %}
    <h2>RH Vagas</h2>
    <div class="form-group">
        <label for="usuario">Usuário</label>
        <input type="text" class="form-control" id="usuario" aria-describedby="usuario" name="usuario">
    </div>
    <div class="form-group">
        <label for="senha">Senha</label>
        <input type="password" class="form-control" id="senha" name="senha">
    </div>
    <br />
    <button type="submit" class="btn btn-success btn-lg btn-block acessar">Acessar</button>
    <hr />
    <div>
    Ainda não possui acesso?
    <br />
    <a class="btn btn-primary btn-lg btn-block acessar" href="{% url 'Pessoa:cadastro'%}" role="button">Cadastre-se</a>
    </div>
    <hr />
    <a href="{% url 'Vagas:pesquisa_vagas' %}">Clique aqui para ver as vagas disponíveis</a>

    {% if messages %}
    {% for message in messages %}
        <div class="alert {{ message.tags }} m-2" id="msg" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %} 

</form>
{% endblock %}